[package]
name = "dag-cbor-derive"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "ipld cbor codec proc macro"
repository = "https://github.com/ipfs-rust/rust-ipld"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.12"
quote = "1.0.4"
syn = "1.0.19"
synstructure = "0.12.3"

[dev-dependencies]
libipld = { path = ".." }
trybuild = "1.0.26"
