[package]
name = "dag-cbor-derive"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.8"
quote = "1.0.2"
syn = "1.0.15"
synstructure = "0.12.3"

[dev-dependencies]
failure = "0.1.6"
dag-cbor = { path = "../dag-cbor" }
libipld = { path = ".." }
libipld-macro = { path = "../macro" }
trybuild = "1.0.23"
