[package]
name = "libipld"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "library for dealing with ipld"
repository = "https://github.com/ipfs-rust/rust-ipld"

[dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
dag-cbor = { version = "0.1.0", path = "dag-cbor", optional = true }
dag-cbor-derive = { version = "0.1.0", path = "dag-cbor-derive", optional = true }
dag-json = { version = "0.1.0", path = "dag-json", optional = true }
dag-pb = { version = "0.1.0", path = "dag-pb", optional = true }
libipld-core = { version = "0.1.0", path = "core" }
libipld-macro = { version = "0.1.0", path = "macro" }
thiserror = "1.0.16"

[dev-dependencies]
criterion = "0.3.2"
proptest = "0.9.6"
model = "0.1.2"

[features]
default = ["dag-cbor", "derive"]
derive = ["dag-cbor-derive"]

[workspace]
members = [
  "core",
  "dag-cbor",
  "dag-cbor-derive",
  "dag-json",
  "dag-pb",
  "macro",
]

[profile.release]
debug = true

[[bench]]
name = "codec"
harness = false

[[bench]]
name = "store"
harness = false
