[package]
name = "libipld"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
async-std = "0.99"
async-trait = "0.1"
byteorder = "*"
cid = { git = "https://github.com/dvc94ch/rust-cid", branch = "cli" }
dag-cbor = { path = "dag-cbor" }
dag-cbor-derive = { path = "dag-cbor-derive" }
failure = "0.1"
futures-preview = { version = "=0.3.0-alpha.18", features = ["async-await", "nightly"] }
libipld-base = { path = "base" }
libipld-macro = { path = "macro" }
multibase = { git = "https://github.com/multiformats/rust-multibase" }
multihash = { git = "https://github.com/dvc94ch/rust-multihash", branch = "cli" }

[dev-dependencies]
criterion = "0.3"
proptest = "0.8"
model = "0.1"

[workspace]
members = [
  "base",
  "macro",
]

[profile.release]
debug = true

[[bench]]
name = "store"
harness = false
