[package]
name = "libipld"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
async-std = "1.5.0"
async-trait = "0.1.24"
byteorder = "1.3.4"
cid = { git = "https://github.com/dvc94ch/rust-cid", branch = "cli" }
dag-cbor = { path = "dag-cbor" }
dag-cbor-derive = { path = "dag-cbor-derive" }
failure = "0.1.6"
futures = "0.3.4"
libipld-base = { path = "base" }
libipld-macro = { path = "macro" }
multibase = { git = "https://github.com/multiformats/rust-multibase" }
multihash = { git = "https://github.com/dvc94ch/rust-multihash", branch = "cli" }

[dev-dependencies]
criterion = "0.3.1"
proptest = "0.9.5"
model = "0.1.2"

[workspace]
members = [
  "base",
  "dag-cbor",
  "dag-cbor-derive",
  "macro",
]

[profile.release]
debug = true

[[bench]]
name = "store"
harness = false
