[package]
name = "libipld"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
async-std = { version = "0.99", default-features = false, features = ["std"] }
async-trait = "0.1"
byteorder = "*"
cid = { git = "https://github.com/datalove-app/rust-cid", branch = "cli" }
dag-cbor = { path = "dag-cbor" }
dag-cbor-derive = { path = "dag-cbor-derive" }
failure = "0.1"
futures = "0.3"
libipld-base = { path = "base" }
libipld-macro = { path = "macro" }
multibase = { git = "https://github.com/multiformats/rust-multibase" }
multihash = "0.9"

[dev-dependencies]
criterion = "0.3"
proptest = "0.8"
model = "0.1"

[workspace]
members = [
  "base",
  "macro",
  "schema"
]

[profile.release]
debug = true

[[bench]]
name = "store"
harness = false
