[package]
name = "libipld-macro"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
libipld-base = { path = "../base" }
multihash = "0.10.1"
