[package]
name = "dag-cbor"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
async-std = { version = "0.99", default-features = false, features = ["std"] }
async-trait = "0.1"
byteorder = "1.3"
bytes = { version = "0.5", optional = true }
failure = "0.1"
libipld-base = { path = "../base" }

[dev-dependencies]
async-std = { version = "0.99", features = ["std"] }
libipld-macro = { path = "../macro" }

[features]
default = []
bytes_ = ["bytes"]
