[package]
name = "libipld-core"
version = "0.3.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Base traits and definitions used by ipld codecs."
repository = "https://github.com/ipfs-rust/rust-ipld"

[dependencies]
cid = { version = "0.5.1", path = "../../rust-cid" }
multibase = "0.8.0"
multihash = { version = "0.11.2", path = "../../rust-multihash" }
thiserror = "1.0.19"

[features]
dag-cbor = []
dag-json = []
dag-pb = []
