[package]
name = "libipld-pb"
version = "0.14.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "ipld protobuf codec"
repository = "https://github.com/ipfs-rust/rust-ipld"

[dependencies]
libipld-core = { version = "0.14.0", path = "../core" }
prost = "0.11"
thiserror = "1.0.25"

[build-dependencies]
prost-build = "0.11"
protobuf-src = "1.1.0"

[dev-dependencies]
libipld-macro = { path = "../macro" }
multihash = "0.16.0"
