[package]
name = "libipld_schema"
version = "0.0.1"
authors = ["sunny-g <sunny.gonna@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
libipld = { path = "../" }
libipld-macro = { path = "../macro" }
