[package]
name = "libipld-base"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
cid = { git = "https://github.com/multiformats/rust-cid" }
multihash = "0.10.0"
failure = "0.1.7"
